default world io {
    import storage: interface {
        insert: func(key : list<u8>, value : list<u8> )
        get: func(key : list<u8>) -> option<list<u8>>
        remove: func(key : list<u8>) -> bool
    }
    import event: interface {
        emit : func(event : list<u8>)
    }

    import log: interface {
       print : func(output : list<char>)
    }
}
